### ISSUE TITLE
Glue availability check failed due to missing permission

### ISSUE THREAD

**Issue by matthias-pichler-warrify** [dacort/metabase-athena-driver#105]
It seems that the sample policy in the readme is missing `glue:GetCatalogImportStatus`

I got the following error:

> Jun 22 14:32:00.128 DEBUG 699 com.simba.athena.athena.api.AJClient.checkGlueSupport: An exception was caught during AWS Glue availability detection operation. Detail: com.simba.athena.amazonaws.services.glue.model.AccessDeniedException: User: arn:aws:sts::xxxxx:assumed-role/metabase-service-prod-TaskRole30FC0FBB-R2HVOCHLUUGP/a499929205b74b0ca2e3f65456e66625 is not authorized to perform: glue:GetCatalogImportStatus on resource: arn:aws:glue:eu-west-1:xxxxx:catalog because no identity-based policy allows the glue:GetCatalogImportStatus action (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: e8fb47f5-70a2-4c43-81e2-95af8b11fdc3; Proxy: null)

**Comment by matthias-pichler-warrify** [comment]
It might be related to the fact that I have AWS LakeFormation enabled in this account

**Comment by dacort** [comment]
Ah yep, that was going to be a guess of mine. Thanks for that extra detail!

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues).
