### ISSUE TITLE
Compatibility with Metabase v.0.44.2

### ISSUE THREAD

**Issue by julianste** [dacort/metabase-athena-driver#108]
First of all thanks @dacort for all your work 👏 

More like a question: the latest release claims to support metabase v.0.43.1 - yet [this commit](https://github.com/dacort/metabase-athena-driver/commit/64b1853757904e596b5f58c90cd870565c282bc9) suggests that metabase 0.44.2 is also supported.

did someone successfully test this adapter with metabase 0.44.2?
thanks

**Comment by dacort** [comment]
Hi @julianste - Yes, the claim is largely which version of Metabase I've _tested_ with the plugin. In many cases, though, newer versions of Metabase will work fine. I did try it out with 0.44.2, so go ahead and take a shot! If something doesn't work, feel free to open an issue. :)
