### ISSUE TITLE
Athena Views support?

### ISSUE THREAD

**Issue by chwonghk01** [dacort/metabase-athena-driver#11]
First of all, thanks for the great plugin! 

However it seems that currently the driver only support tables but not views in Athena. Is this known issue? Any plan to support Athena views?

**Comment by dacort** [comment]
Ah, good catch. Yes, would definitely like to support views.

[`get-tables`](https://github.com/dacort/metabase-athena-driver/blob/a9cb9a237bc0dd46f2e0e724a9bdb95fa1b1abf1/src/metabase/driver/athena.clj#L166) will need to get updated to be able to identify those. I believe the table type comes back as `VIRTUAL_VIEW`.

**Comment by jamarzka** [comment]
It does but there is an issue with how the queries are built still. Currently all columns are formatted database.table.column and that doesn't work when using a view. It can't include the database.

**Comment by dacort** [comment]
@jamarzka Do you have an example of how you query views using the JDBC driver?

**Comment by lukealexmiller** [comment]
Unless I misunderstand the previous comments, Athena views remain unsupported. Is a PR expected for this any time soon? Would be great to be able to use Athena views. Thanks for the great work on the plugin!

**Comment by dacort** [comment]
@lukealexmiller Correct, views remain unsupported. I'm in the codebase this week, so I'll try to get a level of effort for what it would take to support views, but no work is currently planned to implement them. That may change depending on the investigation.

**Comment by vaibhav-acko** [comment]
@dacort - Does athena view support coming soon? We are also looking to query views from metabase.

**Comment by chrispruitt** [comment]
It looks like the views are working when writing custom queries, however they are not shown as a part of the DB schema. So we are unable to create any Field Filters from the view columns, among other features. Also higher level users are unable to choose a view as a data source for a simple question.

**Comment by dacort** [comment]
I unfortunately haven't been able to get around to adding support for them yet, sorry.

**Comment by jainanuj07** [comment]
Hello, 
I am able to connect athena using this driver. But it only showing my one catalogs i have created multiple catalogs in Athena like glue catalog, hive metastore catalog.

How can i get all catalogs in metabase using this driver.

**Comment by dacort** [comment]
I think the right thing to do here is add `VIRTUAL_VIEW` into the list of table patterns in the `get-tables` function.

Note that I'm also planning on upgrading the Athena JDBC driver and, as part of that, there's a new option to map virtual views to views. But it should be easy enough to add support for virtual views. We still need a custom `get-tables` to deal with the fact that tables show up as `EXTERNAL_TABLE`.
