### ISSUE TITLE
Driver doesn't work anymore on latest metabase version 0.44.3 

### ISSUE THREAD

**Issue by elseagle** [dacort/metabase-athena-driver#111]
I get the error below whenever I try to connect to athena:
> No suitable driver found for jdbc:awsathena://athena.eu-west-1.amazonaws.com:443
<img width="801" alt="Screenshot 2022-10-18 at 11 31 45" src="https://user-images.githubusercontent.com/27138575/196406829-abb6d597-e13d-4562-9f7e-087491545bab.png">

This driver works fine on 0.36.3 but I upgraded and this error keeps popping up

**Comment by dacort** [comment]
Hi @elseagle - Did you upgrade the driver, your Metabase version, or both?

The driver is tested with certain versions of Metabase and occasionally the versions are incompatible. If you upgraded to Metabase v0.44.4, you'll likely need to upgrade to v1.4.0 of the driver. I list the versions I test each release with on the [releases](https://github.com/dacort/metabase-athena-driver/releases) page.

**Comment by elseagle** [comment]
Thanks, @dacort - I was on v1.1.0, will upgrade

**Comment by dacort** [comment]
Awesome, sounds good! I'll close this issue for now, but feel free to reopen or create a new one if you run into any issues!
