### ISSUE TITLE
Chart do not work while selecting date range in days/weeks/months 

### ISSUE THREAD

**Issue by panditrahulsharma** [dacort/metabase-athena-driver#115]
Hey All,
I am trying to show some charts on dashboard. Chart do not work while selecting date range in days/weeks/months. It is only working while selecting the actual date range like 01-07-2022 etc.
The error which I am getting is below:

![alt text](https://discourse.metabase.com/uploads/default/original/2X/c/c6a8892ee335a1e73a11bb04c6df8e7795914d3f.png
)

![alt text](https://discourse.metabase.com/uploads/default/original/2X/d/d4971c48504ca2074929599d27512e9b4b86a224.jpeg)

**Comment by juliansteger-sc** [comment]
We face a similar issue. Using Athena Version 3, casting from `timezone with time zone` to `timestamp` is not supported anymore.
We have query builder queries that use something like
`cast(now() as timestamp)` and this is not possible anymore, since `now()` returns `timestamp with time zone` type.

would be great if this could be fixed, the workaround for us right now is to convert those queries to native SQL queries.

**Comment by dacort** [comment]
Ah interesting, is this only in v3 @juliansteger-sc ? v2 works fine?

**Comment by juliansteger-sc** [comment]
Didn't try that specifically but I would think so, we never had issues.
```
cast(now() as timestamp)
```
works in Athena v2 and would return the current time utc (without time zone).

But it doesn't work in Athena v3 anymore:
```
NOT_SUPPORTED: Casting a Timestamp with Time Zone to Timestamp is not supported
```
One workaround we use is `select from_unixtime(to_unixtime(now() at time zone 'UTC'))`

The breaking change is also mentioned in the [AWS Docs](https://docs.aws.amazon.com/athena/latest/ug/engine-versions-reference-0003.html):

#### Casting from TimestampTZ to Timestamp is not supported
Error Message: Casting a Timestamp with Time Zone to Timestamp is not supported.

**Suggested Solution**: Any explicit or implicit cast from TimestampTZ to Timestamp throws the exception. If possible, remove the cast and use a different data type.

**Comment by dacort** [comment]
Interesting, thanks for the additional detail @juliansteger-sc - I'll have to take a peek and see if I can easily replace the areas I cast things. Will try to do so in the next couple of days!

**Comment by dacort** [comment]
Just released [v1.5.1](https://github.com/dacort/metabase-athena-driver/releases/tag/v1.5.1) to fix this - feel free to give it a shot and let me know.

**Comment by juliansteger-sc** [comment]
@dacort works like a charm, thanks for the quick fix!
It's really incredible how you keep this project running 🚀

**Comment by dacort** [comment]
Much appreciated @juliansteger-sc :) Truly a labor of love for a couple of my favorite products.
