### ISSUE TITLE
Athena Query Result feature not working

### ISSUE THREAD

**Issue by juliansteger-sc** [dacort/metabase-athena-driver#118]
There's a new Athena Caching feature that was announced just recently - this would be a great feature to have in combination with this driver: 
https://aws.amazon.com/blogs/big-data/reduce-cost-and-improve-query-performance-with-amazon-athena-query-result-reuse/

> If you use the JDBC or ODBC driver to query Athena, you can now add enableResultReuse=1 to your connection parameters to enable Query Result Reuse, and use ageforResultReuse=60 to set the maximum age to 60 minutes. The drivers automatically apply the setting to all queries running in the context of the connection.

I know it's a driver feature, but just to make sure, should this be working by configuring
`enableResultReuse=1;ageforResultReuse=60` for the Additional Athena connection string options?
I don't see a new driver version released, and its also not yet mentioned in the jdbc driver docs.

Downside is, that Metabase includes the userID in the query top level comment, and Athena Cache treats different comments as different queries.

**Comment by dacort** [comment]
Yes, you should be able to just add those to the connection string options. Alas, I don't think there's anything I can do to address the userID.

**Comment by juliansteger-sc** [comment]
According to AWS support, the jdbc driver does not support this feature as of now:

> Upon further investigation and going through the various documents and jdbc driver release notes [1],[2] I want to inform you that unfortunately as of now the query reuse feature is not available for the version 42-2.0.33.I request you to be patient by the time new versions of driver start supporting this feature,meanwhile the query reuse feature works perfectly fine on the console and you can try using the same.

So I'm going to close this issue, there's nothing to do for this adapter.

**Comment by dacort** [comment]
Awesome, appreciate you following up @juliansteger-sc !
