### ISSUE TITLE
Feature Request: Cache feature of metabase for athena driver

### ISSUE THREAD

**Issue by ravishanker404** [dacort/metabase-athena-driver#15]
Currently the athena plugin does not support the caching feature of metabase.

We quite a few metric dashboards running. 
Problems with no cache:
 - AWS service limits
 - Some of the queries take quite a few minutes to run, which delays the dashboard load

We would ideally want these to be cached.

**Comment by dacort** [comment]
Ah, interesting, didn't realize it was something that had to be supported by the plugin. Will try to take a look soon to estimate a level of effort to support that.

**Comment by dacort** [comment]
@ravishanker404 I just tried this out in Metabase 0.32.5 and it seems to work. 

What do your caching settings look like? 

I set mine to some high values just to test and it seems to work. 
![image](https://user-images.githubusercontent.com/1512/62325565-c6ff7000-b460-11e9-8bd4-67ca86181b6d.png)

**Comment by dacort** [comment]
Closing this as won't fix as it looks like caching is not a driver-specific setting.
