### ISSUE TITLE
feature request: option to use DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by mikepii** [dacort/metabase-athena-driver#16]
When deployed to AWS EC2, it's best to use instance profile credentials delivered through the Amazon EC2 metadata service, which are considered more secure than using long-lived tokens. The Athena JDBC driver docs say that `DefaultAWSCredentialsProviderChain` is supported. That would enable the standard list of credential provider options including instance profile credentials, environment variables, and JVM system properties.

I'd be glad to implement this and submit a PR if it makes sense.

**Comment by dacort** [comment]
Oh nice, thanks for the suggestion @mikepii!

This isn't likely something I'll implement in the near future, so feel free to go ahead.

I'd imagine we'd need the option on the settings page to leave the credentials blank. Don't think there's a way to have a toggle option or something like that.
