### ISSUE TITLE
Connection timeout though data is being created

### ISSUE THREAD

**Issue by schmitzke** [dacort/metabase-athena-driver#25]
Hi there,

I installed the driver from the latest release and my metabase interface gives me the proper form to fill in my credentials for athena. I created an empty bucket and on "Save" I end up getting metadata as .txt and .csv inside my bucket, but metabase tells me the connection timed out.
I *did* set the ENV to have 10 second timeout. This did not help. I assume my credentials are correct because metabase is writing into my bucket. Here are the logs from my system:

`[ea90e48c-6a84-4ac9-865c-0a0938c5c854] 2019-12-10T15:33:23+01:00 ERROR metabase.driver.util Database connection error
[ea90e48c-6a84-4ac9-865c-0a0938c5c854] 2019-12-10T15:33:23+01:00 DEBUG metabase.middleware.log POST /api/database 400 10.0 s (0 DB calls)
{:valid false, :dbname "Timed out after 10,000 milliseconds.", :message "Timed out after 10,000 milliseconds."}`

**Comment by dacort** [comment]
Hey @schmitzke - what region is your S3 bucket in, what region did you select for Athena, and where are you trying to run Metabase from? It's totally possible that you may need to raise the timeout even more. 

If that still doesn't work, can you verify that you can access the Athena endpoint on port 443? For example, for us-east-1, this is the endpoint `http://athena.us-east-1.amazonaws.com/`. Maybe try doing a `curl -v http://athena.us-east-1.amazonaws.com/` to see if that works?

**Comment by schmitzke** [comment]
Hey, thanks for the quick reply. 
My metabase is setup locally with docker. I raised the timeout to 25 seconds, still no success.

Then I installed curl inside my docker container and got:

`bash-4.4# curl -v http://athena.eu-central-1.amazonaws.com/
* Expire in 0 ms for 6 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 0 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 1 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 2 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 3 ms for 1 (transfer 0x562b3d89a680)
* Expire in 3 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 4 ms for 1 (transfer 0x562b3d89a680)
* Expire in 8 ms for 1 (transfer 0x562b3d89a680)
* Expire in 5 ms for 1 (transfer 0x562b3d89a680)
* Expire in 5 ms for 1 (transfer 0x562b3d89a680)
* Expire in 8 ms for 1 (transfer 0x562b3d89a680)
* Expire in 6 ms for 1 (transfer 0x562b3d89a680)
* Expire in 6 ms for 1 (transfer 0x562b3d89a680)
* Expire in 8 ms for 1 (transfer 0x562b3d89a680)
* Expire in 8 ms for 1 (transfer 0x562b3d89a680)
* Expire in 8 ms for 1 (transfer 0x562b3d89a680)
* Expire in 11 ms for 1 (transfer 0x562b3d89a680)
*   Trying 35.157.58.174...
* TCP_NODELAY set
* Expire in 149982 ms for 3 (transfer 0x562b3d89a680)
* Expire in 200 ms for 4 (transfer 0x562b3d89a680)`

and then it basically hangs up forever. So your guess was right. I will see what I can find on google - if you have a suggestion, help is appreciated but feel free to close the issue since it does not apply to your software. Thank you!

**Comment by dacort** [comment]
Oh, sorry, I pasted an http link when it should have been https. Can you try the curl with that instead?

```shell
curl -v https://athena.eu-central-1.amazonaws.com/
```

**Comment by schmitzke** [comment]
Totally makes sense to use https...I didn't notice either. Strange thing is I googled something like "docker container no internet" and the summary of my research was that my nameserver settings are incorrect inside my container. BUT curling Athena via https seems to work:

`*   Trying 52.58.107.26...
* TCP_NODELAY set
* Expire in 149973 ms for 3 (transfer 0x55f9c6bb2680)
* Expire in 200 ms for 4 (transfer 0x55f9c6bb2680)
* Connected to athena.eu-central-1.amazonaws.com (52.58.107.26) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=athena.eu-central-1.amazonaws.com
*  start date: Aug  8 00:00:00 2019 GMT
*  expire date: Sep  8 12:00:00 2020 GMT
*  subjectAltName: host "athena.eu-central-1.amazonaws.com" matched cert's "athena.eu-central-1.amazonaws.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: athena.eu-central-1.amazonaws.com
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Thu, 12 Dec 2019 08:28:57 GMT
< x-amzn-RequestId: b238214d-e829-4fb5-ab7e-21c841851e6c
< Content-Length: 127
< Connection: keep-alive
<
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
* Connection #0 to host athena.eu-central-1.amazonaws.com left intact`

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues).
