### ISSUE TITLE
Specify database during setup

### ISSUE THREAD

**Issue by dacort** [dacort/metabase-athena-driver#3]
The driver currently syncs all databases and all tables - this may not be desirable behavior.

**Comment by bryanyang0528** [comment]
It's a very import feature! I've tried to use IAM to restrict the permission of reading databases, but the driver will return error if the IAM have no permission to read the database in the Glue category.

**Comment by vitalybibikov** [comment]
Hm, 
just paid extra 3k just  for a day running the Athena plugin, because it was scanning the whole rest of the dbs in the region constantly. Noticed only after high consumption alert.

So, db selection is much desired =)

**Comment by dacort** [comment]
This was implemented. Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45).
