### ISSUE TITLE
Add assume role option if running metabase in an AWS environment

### ISSUE THREAD

**Issue by chrispruitt** [dacort/metabase-athena-driver#32]
I am currently running Metabase from a docker image on ecs. It would be awesome if the athena driver would allow an option to assume the role of the ecs task instead of passing in aws access keys. Or make them optional and, by default, assume the ecs task role.

**Comment by dacort** [comment]
Hi @chrispruitt - In #17 support for using the EC2 instance profile credentials was added. Will this work in the ECS environment? You can try it by just leaving out the access keys in the DB config.

**Comment by chrispruitt** [comment]
Hey @dacort, that does work! thanks for the quick response. I'll go ahead and close.
