### ISSUE TITLE
No suitable driver found for jdbc:awsathena://athena.us-west-2.amazonaws.com

### ISSUE THREAD

**Issue by KiranPanesar** [dacort/metabase-athena-driver#34]
I followed the guide IAM policy, but I'm getting the following error when trying to set up the database. A POST to `localhost:3000/api/database` returns:
```json
{"valid":false,"dbname":"No suitable driver found for jdbc:awsathena://athena.us-west-2.amazonaws.com:443","message":"No suitable driver found for jdbc:awsathena://athena.us-west-2.amazonaws.com:443"}
```
Any suggestions?

**Comment by KiranPanesar** [comment]
It appears that this is an issue with our AWS setup. Will close to for now.

**Comment by JadCham** [comment]
It looks like the Athena driver isn't working (same issue as above) on newer versions of Metabase >= 0.35.0.

I rolled back from 0.35.1 to 0.34.3 and it worked again normally.

Any thoughts @dacort?  Is this an issue that should be filed on Metabase?

**Comment by dacort** [comment]
Hi @JadCham - Yes, the most [recent release](https://github.com/dacort/metabase-athena-driver/releases/tag/v0.3.0) is only compatible with 0.34.x.

I added #35 (hah!) to address 0.35 compatibility and will be addressing in a week or two.

**Comment by JadCham** [comment]
> Hi @JadCham - Yes, the most [recent release](https://github.com/dacort/metabase-athena-driver/releases/tag/v0.3.0) is only compatible with 0.34.x.
> 
> I added #35 (hah!) to address 0.35 compatibility and will be addressing in a week or two.

That's awesome thank you!
