### ISSUE TITLE
Version 0.35 upgrade

### ISSUE THREAD

**Issue by dacort** [dacort/metabase-athena-driver#35]
Metabase 0.35 has some [breaking change](https://github.com/metabase/metabase/wiki/What's-new-in-0.35.0-for-Metabase-driver-authors).

Need to update the driver to reflect that.

**Comment by aipymhx** [comment]
we badly need this !!!

**Comment by dacort** [comment]
Hi @aipymhx - nice to hear you're making use of the driver. I hope to be able to get to this in the next week or two. Please understand this is a project I maintain in my spare time.
