### ISSUE TITLE
Please add support for China Region

### ISSUE THREAD

**Issue by neptune19821220** [dacort/metabase-athena-driver#40]
Dear Developer:

I find your Athena driver doesn't support China Region due to the endpoint difference.
For Athena endpoint list : https://docs.aws.amazon.com/general/latest/gr/athena.html
The China regions all ends with amazonaws.com.cn instead amazonaws.com.

And the config document , https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.9/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf  , the EndpointOverride config seems not change the suffix of the endpoint.

Thanks.

**Comment by dacort** [comment]
Hi @neptune19821220 - thanks for filing the new issue re: China support!

I'll just have to make a small change in the code to support this. Currently it's [hardcoded](https://github.com/dacort/metabase-athena-driver/blob/c9f38b871c213949d29cbafc98455ba583a2cb26/src/metabase/driver/athena.clj#L55) to `amazonaws.com`. 

I should be able to have a fix for this within a week or so.

**Comment by hbuzhuhaoju** [comment]
I used  your latest Athena driver ,v1.10, but driver also throw exception for  China region；

An error has been thrown from the AWS SDK client. Unable to execute HTTP request: athena.cn-north-1.amazonaws.com: Name or service not known [Execution ID not available]

Please forgive my bad english

**Comment by hbuzhuhaoju** [comment]
@dacort
