### ISSUE TITLE
Building from source - Multiple Systems Error java_time__init.class

### ISSUE THREAD

**Issue by cabarria** [dacort/metabase-athena-driver#43]
I've tried to build from source following the instructions on separate systems (Amazon Linux, Ubuntu 14,18,20 and MAC OSX 10.14.6) with multiple java versions from OpenJDK/Oracle/Adopt, yet all give me the same error.:

Caused by: java.io.FileNotFoundException: Could not locate java_time__init.class, java_time.clj or java_time.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.

Here are the versions I'm using on OSX
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
Leiningen 2.9.3 on Java 1.8.0_251 Java HotSpot(TM) 64-Bit Server VM
yarn 1.22.4

The JDBC driver is at the correct location:
~/.m2/repository/athena/athena-jdbc/2.0.9/
athena-jdbc-2.0.9.jar

I'm trying to get a build with the preview [https://athena-downloads.s3.amazonaws.com/drivers/JDBC/athena-preview/SimbaAthenaJDBC_2.0.11_preview/AthenaJDBC42_preview.jar](url) JDBC driver once I can get the current release to compile.

Any help would be much appreciated.  Thanks

**Comment by dacort** [comment]
Hi @cabarria - thanks for taking a look at the project.

I may need to update my `Contributing` docs. Have you installed `metabase-core` as noted in the [driver docs](https://github.com/metabase/metabase/wiki/Writing-a-Driver:-Packaging-a-Driver-&-Metabase-Plugin-Basics#installing-metabase-core-locally)?

You can do this by running
```shell
lein install-for-building-drivers
```
from the root of the core Metabase repository in the `release-0.35.x` branch.

**Comment by cabarria** [comment]
Yeah that was the issue. I had just started to go over the metabase repo and the development instructions. Thanks!
