### ISSUE TITLE
Query error even if table exists

### ISSUE THREAD

**Issue by aastha-agrawal-1** [dacort/metabase-athena-driver#44]
I am trying to run a SQL command on a table in Athena but it raise an error table not found even if the table exist in the database. Could you please resolve it?

**Comment by heruscoder** [comment]
+1

is this a problem? or we need to use something like "use 'database'" in SQL?

**Comment by dacort** [comment]
You'll need to specify the full database and table in your SQL queries. 

This is behavior of the Athena [JDBC driver](https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.9/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf). 

> By default, the driver queries the default database. To distinguish between tables
in the default and custom databases, when writing your queries, use the database
identifier as a namespace prefix to your table name.

**Comment by orenmazor** [comment]
is there any way to specify a default database?

**Comment by dacort** [comment]
Try adding `Schema` in the additional connection string options, e.g: `Schema=somedb`

**Comment by orenmazor** [comment]
fantastic. thank you. I keep meaning to see what the full spec of those options is. is there a doc somewhere in aws?

**Comment by dacort** [comment]
It’s in the installation and configuration guide: https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.9/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf

(Note it’s version-specific)
