### ISSUE TITLE
Upgradation of metabase

### ISSUE THREAD

**Issue by aastha-agrawal-1** [dacort/metabase-athena-driver#45]
I want to upgrade my metabase version but when I tried it gives me docker image of metabase/metabase. How to upgrade metabase-athena which I am using from this repository?

**Comment by dacort** [comment]
Hi @aastha-agrawal-1 - Unfortunately I'm not quite sure what you're asking.

Can you provide some more details? Maybe a set of steps you're doing to run this and a set of steps you've used to try to upgrade? I'll close this for now, but feel free to comment and I'll reopen it.

**Comment by aastha-agrawal-1** [comment]
Hi @dacort, I am using this metabase-athena-driver using Dockerfile which already has Metabase with the Amazon Athena driver pre-loaded. Now, the upgraded version is released still Metabase shows that I am using 0.35.2 version. Will the version is automatically upgraded in docker or some steps should be followed to upgrade the driver?

**Comment by dacort** [comment]
The Dockerfile is intended as a simple example of incorporating this driver into your own production Metabase Dockerfile. If you want to use a different version of Metabase, you would need to update the file accordingly. I did just update the Dockerfile in this repo to use Metabase v0.36.2 as an example, but you would need to figure out on your own how to incorporate this into a production environment.

I should note that if you have an existing Docker environment configured and running, when you shut it down you will lose any configuration or settings you have made. This isn't unique to this driver, though, Docker images are intended to be ephemeral.
