### ISSUE TITLE
Continuous events in Amazon CloudTrail

### ISSUE THREAD

**Issue by shubhamk-mindtickle** [dacort/metabase-athena-driver#47]
Hello. I recently started using metabase-athena-driver and observed that there are huge number of events in Amazon CloudTrail. I only fired a single query  but there were a lot of events  in CloudTrail. Also these events are coming continuously till the time metabase UI is open resulting in large number of events. Seems like some kind of polling. There are no queries in athena history corresponding to these events. Any reason why these events coming? And is there a way can stop these? Attaching a screenshot for the events. We are flooded with these.

Edit: So I just figured out that it is trying to get the queryExecution. So my question now is that even if there is no query that is pending why is it still hitting getQueryExecution? Is there a way to avoid it?

Athena Driver version: v1.0.0

![image](https://user-images.githubusercontent.com/54264148/86131500-585ce380-bb03-11ea-8172-8459d3db8d1e.png)

**Comment by dacort** [comment]
Hi @shubhamk-mindtickle - Metabase does occasionally sync and scan your database looking for changes, so it's possible this is what's going on here. Take a look at https://www.metabase.com/docs/latest/administration-guide/01-managing-databases.html#database-sync-and-analysis and see if disabling that helps. It won't disable *all* database checks, but may reduce the number of queries.

It's kind of odd that there are no corresponding queries in Athena history.
