### ISSUE TITLE
Unable to view tables in database

### ISSUE THREAD

**Issue by aastha-agrawal-1** [dacort/metabase-athena-driver#48]
I added a redshift database yesterday and i was able to see the data in tables through querying or filtering. But today when i opened the tables to see the data it is just loading and i cannot view data in tables. What is the reason behind this? Even after syncing my database i am unable to see the data.

**Comment by dacort** [comment]
Hi @aastha-agrawal-1 - this repository is specific to the Athena driver. Sounds like you're using Redshift? I would recommend asking on the Metabase forum for troubleshooting help - discourse.metabase.com
