### ISSUE TITLE
No columns

### ISSUE THREAD

**Issue by yyie** [dacort/metabase-athena-driver#57]
Hi, I'm trying to setup Athena as a Metabase database. I already added the driver and configured the database. It detects my tables, but it doesn't detect their columns. Can you please help me? It's an IAM permission problem?

**Comment by dacort** [comment]
Hi @yyie - do you see any errors or warnings in the Metabase server logs? You can find these in the Admin --> Troubleshooting section of Metabase. Please also let me know which version of Metabase and the Athena driver you're using.

**Comment by yyie** [comment]
Hi, thanks for your answer.

I'm using:
* Metabase: 0.36.4
* Athena driver: 1.1.0

I found that the problem was the missing permissions for Athena. Additionally, the IAM policy reports some warnings because there are several athena permissions that doesn't exist. With those changes Metabase is working ok.

This is the AIM policy that i'm using .... 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "athena:GetTableMetadata",
                "athena:StartQueryExecution",
                "athena:ListDataCatalogs",
                "glue:GetTableVersions",
                "glue:GetPartitions",
                "athena:GetQueryResults",
                "athena:GetDatabase",
                "athena:GetDataCatalog",
                "athena:ListWorkGroups",
                "athena:GetNamedQuery",
                "athena:ListQueryExecutions",
                "athena:GetWorkGroup",
                "glue:GetTableVersion",
                "athena:StopQueryExecution",
                "athena:GetQueryResultsStream",
                "glue:GetTables",
                "glue:BatchGetPartition",
                "glue:GetDatabases",
                "athena:ListTagsForResource",
                "glue:GetTable",
                "athena:ListNamedQueries",
                "glue:GetDatabase",
                "glue:GetPartition",
                "athena:ListDatabases",
                "athena:GetQueryExecution",
                "athena:BatchGetNamedQuery",
                "athena:ListTableMetadata",
                "athena:BatchGetQueryExecution"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::xxxxxxxxxxxxx",
                "arn:aws:s3:::xxxxxxxxxxxxx/*"
            ]
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:AbortMultipartUpload",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::xxxxxxxxxxxxx",
                "arn:aws:s3:::xxxxxxxxxxxxx/*"
            ]
        }
    ]
}

**Comment by dacort** [comment]
Thanks, @yyie! That makes sense - I think the main one is `athena:ListDataCatalogs` but there may be others. 

This is related to #56 where the upgraded JDBC driver requires additional permissions and I need to update the readme.
