### ISSUE TITLE
Group names not fully visible on screen

### ISSUE THREAD

**Issue by aastha-agrawal-1** [dacort/metabase-athena-driver#58]
I am running metabase on my local machine but under the permissions option, I cannot see the group names properly. Can anyone suggest me what to do?

It is visible like this
![Screenshot from 2020-08-23 16-03-32](https://user-images.githubusercontent.com/31098284/90976507-5d666e00-e55b-11ea-87a1-cdafc1db5077.png)

**Comment by dacort** [comment]
@aastha-agrawal-1 This seems like a Metabase-specific issue, unrelated to the Athena driver. 

I would recommend posting on [the Metabase forum](https://discourse.metabase.com/) to see if somebody can help you debug that. You will need to post "Diagnostic Info" from the Admin --> Troubleshooting section as well as information about your browser.

**Comment by aastha-agrawal-1** [comment]
@dacort Thanks for advice.
