### ISSUE TITLE
Unknown type: float 

### ISSUE THREAD

**Issue by yyie** [dacort/metabase-athena-driver#59]
Hi, I'm having another issue. I'm trying to get a calculated metric that is obtained by the division of two float fields

sum(field1)/sum(field2)

And I got the following error:

[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 2:9: Unknown type: float 

Looking at the logs, the query executes a cast to float to the field1

Do you know if is it a problem with the driver? may be I can change the datatype mappings?

**Comment by yyie** [comment]
Hi Damon, I found the problem. I added a pull request to fix the code

https://github.com/dacort/metabase-athena-driver/pull/60

**Comment by dacort** [comment]
Ah, interesting! Thanks for the PR @yyie - I will try to look at it in the next week or two. I know it's small, but this is a side project for me. 🥰
