### ISSUE TITLE
Create Dockerfiles for source install (beyond just binary install)

### ISSUE THREAD

**Issue by patcon** [dacort/metabase-athena-driver#68]
Hi! Thanks for this wonderful driver. I was pointed here as the best way to learn driver development, and this looks really clear.

Just wanted to make the small suggestion, so people with Docker already set up can build HEAD (and see the high-level build steps laid out from scratch)

`Dockerfile.binary` and `Dockerfile.source` would be clear. Parking this for now, and maybe I'll come back to work on it myself when I'm getting my driver-dev legs underneath me :)

**Comment by dacort** [comment]
Hi @patcon! Thank for stopping by. :) 

This is a really good idea. The other thing I should do is make a proper Dockerfile to auto-build https://hub.docker.com/repository/docker/dacort/metabase-athena-driver
