### ISSUE TITLE
Failing to parse nested array expression

### ISSUE THREAD

**Issue by voroninman** [dacort/metabase-athena-driver#72]
Query:

```sql
SELECT ARRAY[ARRAY[1]]
```

Expected:
```
{[1]}
```

Actual:
```
Output of parse-tokens* does not match schema: [0;33m [(named [nil nil (not (matches-some-precondition? nil))] "parsed tokens") (not (present? "remaining tokens"))] [0m
```

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues).
