### ISSUE TITLE
Metabase 0.38 removed sql.qp/unix-timestamp->timestamp

### ISSUE THREAD

**Issue by shwetamt** [dacort/metabase-athena-driver#74]
It seems there are compatibilty issues of Athena driver (version 1.1.0) with the Metabse 0.38, our service driver is throwing error after we upgraded metabase to 0.38 -> “Attempting to call unbound fn: #'metabase.driver.sql.query-processor/cast-unix-timestamp-field-if-needed”.
Also, it is mentioned in metabase discourse that they have removed the support for unix-timestamp https://discourse.metabase.com/t/changes-in-0-38-for-driver-developers/13473

**Comment by dacort** [comment]
Hi @shwetamt - yes, this is a known issue. I have a pre-release you can test and am hoping to get a new release out this week. Please see https://github.com/dacort/metabase-athena-driver/issues/73 for details. 

Thanks!

**Comment by dacort** [comment]
Updated release for 0.38 support can be found here: https://github.com/dacort/metabase-athena-driver/releases/tag/v1.2.0
