### ISSUE TITLE
Migrating Metabase application data from H2 to MySQL

### ISSUE THREAD

**Issue by thakurshalabh08** [dacort/metabase-athena-driver#76]
Hello there,

I have been using the docker file to start and run Metabase with a pre-loaded Athena driver which by default stores all the application data inside an H2 database. However, now want to configure Metabase to use MySQL instead of H2 as its application database. I know there are some notes on the Metabase website to do this task. However, I'm not sure how to incorporate those configurations inside the docker container. Can you please suggest a way to do it for Metabase with Athena-driver? 

Thank you
Shalabh

**Comment by dacort** [comment]
If this is still an issue, I would suggest asking on the [Metabase forum](https://discourse.metabase.com/) for help.

Closing this issue as part of cleanup.
