### ISSUE TITLE
Allow access to fields of unstructured data in filters and custom expression

### ISSUE THREAD

**Issue by FranzBusch** [dacort/metabase-athena-driver#77]
I have a column that contains unstructured JSON data. Would it be possible to access these nested fields in the filters and custom expressions somehow?

**Comment by dacort** [comment]
I'm not sure about native filters (Metabase would have to add [support for JSON data](https://github.com/metabase/metabase/issues/708) first).

A couple potential workarounds using [`json_extract`](https://docs.aws.amazon.com/athena/latest/ug/extracting-data-from-JSON.html):
- Create a view in Athena with the desired fields extracted from the JSON
- Use SQL to extract the fields and then create filters on that SQL question

**Comment by FranzBusch** [comment]
I opted to create a view in Athena for now. Let's see if Metabase adds support for this in the future.

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). 

See https://github.com/metabase/metabase/issues/26972 for a similar issue.
