### ISSUE TITLE
When writing a custom SQL query with a date filter variable it returns an error

### ISSUE THREAD

**Issue by FranzBusch** [dacort/metabase-athena-driver#78]
I wrote a custom query and used a `{{day}}` variable which I set to be a date filter. When executing the query I run into an error from Athena

```
[Simba][AthenaJDBC](100071) An error has been thrown from the AWS Athena client. SYNTAX_ERROR: line 4:131: Unexpected parameters (varchar(3), varchar) for function date_trunc. Expected: date_trunc(varchar(x), date) , date_trunc(varchar(x), time) , date_trunc(varchar(x), time with time zone) , date_trunc(varchar(x), timestamp) , date_trunc(varchar(x), timestamp with time zone) [Execution ID: bc32b83e-7dd5-4596-ad0c-5b790f3f2147]
```

The query looks like this:

```
SELECT *
FROM "table"
WHERE {{day}}
```

**Comment by dacort** [comment]
Hi @FranzBusch - can you provide more details on the schema of your table, what data type you're mapping the `day` variable to in Metabase, and what you're trying to map `{{day}}` to? Based on the error message, it looks the field you're trying to map it to is a string field and not a date/time field.

**Comment by FranzBusch** [comment]
Okay I checked again how the columns are in Athena and in Metabase. So my date column in Athena looks like this `2020-02-10` and in Metabase it is a `Text as ISO-8601 date`.

**Comment by FranzBusch** [comment]
Okay, I think that is actually the reason for this not working. If I create a new column based on my date column that is casted to a timestamp it works with native queries. Since regular dashboard filters are working with my normal date column, I think it is a bug in handling `Text as ISO-8601 date` columns in native queries with Athena.

**Comment by dacort** [comment]
Thanks, @FranzBusch - I think that's a relatively new feature so could definitely explain the issue. I'll try to dig in this week or next and see if there's a way to address this. 

In the time being, a workaround might be to either set the column explicit to Text in Metabase, or add a date conversion function in your SQL.

**Comment by dacort** [comment]
Closing as part of cleanup now that [Athena is officially supported by Metabase](https://www.metabase.com/releases/Metabase-0.45). Any future issues can be asked about on their [forum](https://discourse.metabase.com/) or with a detailed [bug report](https://github.com/metabase/metabase/issues).
