### ISSUE TITLE
Specific athena database to sync with Metabase

### ISSUE THREAD

**Issue by thakurshalabh08** [dacort/metabase-athena-driver#79]
Hello there,

On linking Metabase with Athena, by default, all Athena databases under the AWS account get synced with Metabase. However, we are looking at putting only some specific Athena databases/tables in Metabase. Is there a way to specify in Metabase or Athena Driver which database or table should be sync?

**Comment by dacort** [comment]
Not at this time, but you can upvote #3 if you like!
