### ISSUE TITLE
ListDataCatalogue

### ISSUE THREAD

**Issue by acountrec** [dacort/metabase-athena-driver#83]
I get the following error: "is not authorized to perform: athena:ListDataCatalogs"

Now I know this could be fixed by getting the rights but is there an easier way to make sure the driver is not listing it and just uses the default catalog: "AwsDataCatalog" ?

**Comment by acountrec** [comment]
Couldn't really find anything in the settings of JDBC. But also didn't really find anything in the source code about this, so I'm a little confused.

**Comment by acountrec** [comment]
Closing, ill use an older version instead. Actually also noticed I wasn't assuming the right role.

**Comment by dacort** [comment]
Hi @acountrec - Let me know if you have any other issues. There's an example [iam policy](https://github.com/dacort/metabase-athena-driver#example-iam-policy) in the README of the project if that helps.
