### ISSUE TITLE
Managed Tables are Not Synced in Metabase

### ISSUE THREAD

**Issue by jpugliesi** [dacort/metabase-athena-driver#91]
We have some AWS Glue tables that are Managed tables, as opposed to External tables (see the [difference described here in the Hive docs](https://cwiki.apache.org/confluence/display/Hive/Managed+vs.+External+Tables))

Using this driver, only external tables are successfully synced and show up in Metabase - managed tables never do. I couldn't find this behavior documented anywhere, so wanted to clarify if this a known limitation and/or what it would require to support this.

In any case, appreciate this project and its contribution to extending the Metabase ecosystem

**Comment by dacort** [comment]
Yep, it's hard-coded [here](https://github.com/dacort/metabase-athena-driver/blob/762dad289433895f982104761aec1f6e16c9a7df/src/metabase/driver/athena.clj#L248) to only look for certain table types. 

We could probably add managed tables (`MANAGED_TABLE`) to that list.

**Comment by jpugliesi** [comment]
Thanks for the help @dacort - created https://github.com/dacort/metabase-athena-driver/pull/93 to address this
